config/routes.rb
Rails.application.routes.draw do
  root 'polls#index'
  resources :polls
  get 'poll/:id/view_responses' => 'polls#view_responses', as: 'view_responses'
  resources :responses

end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :poll

  def to_s
    self.answer
  end
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :options
  has_many :responses
  accepts_nested_attributes_for :options, :reject_if => :all_blank, :allow_destroy => true
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :poll

  serialize :answer
  before_save :remove_empty_string

  def remove_empty_string
    if answer.class == Array
      answer.reject!(&:empty?)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def view_responses
    @poll = Poll.includes(:responses).find(params[:id])
    @responses = @poll.responses
  end

  def save_poll_response
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit!
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    @poll = Poll.find(params[:poll])
    @response = Response.new
  end

  def create
    @response = Response.new(response_params)
    if @response.save
      redirect_to polls_path, notice: 'Thanks for voting'
    else
      render :new
    end
  end

  private

  def response_params
    params.require(:response).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polls/_form.html.erb
<%= simple_form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>
      <ul>
      <% @poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :question %><br>

  <h3>Options</h3>

  <%= f.input :answer_type, label: 'Display options as:', collection: ['radio_buttons', 'check_boxes'] %><br>
  <div>
    <%= f.fields_for :options do |option| %><br>
      <%= render 'option_fields', f: option %>
    <% end %>
    <hr>
    <%= link_to_add_association 'Add an option', f, :options %>
  </div>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/polls/_option_fields.html.erb
<div class='nested-fields'>
  <%= f.input :answer %>
  <%= link_to_remove_association 'Remove this option', f %>
</div>

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<h1>Listing polls</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= poll.question %></td>
        <td><%= poll.answer_type %></td>
        <td><%= link_to 'Show', poll %></td>
        <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
        <td><%= link_to 'Take Poll', new_response_path(poll: poll) %></td>
        <td><%= link_to 'View Responses', view_responses_path(poll) %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path %>

app/views/polls/new.html.erb
<h1>New poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @poll.question %>
</p>

<p>
  <strong>Answer type:</strong>
  <%= @poll.answer_type %>
</p>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

app/views/polls/view_responses.html.erb
<h1><%= @poll.question %></h1>

<h2>Responses</h2>
<ol>
  <% @responses.each do |response| %>
  <li><%= response.answer %></li>
  <% end %>
</ol>

app/views/responses/new.html.erb
<h1>Take Poll</h1>

<h2><%= @poll.question %></h2>

<%= simple_form_for(@response) do |f| %>
  <%= f.input :poll_id, as: :hidden, input_html: { value: params[:poll] } %>
  <%= f.input :answer, label: false, collection: @poll.options.map(&:answer), as: @poll.answer_type %>
  <%= f.submit %>
<% end %>